### Products index action

GET http://localhost:3000/products
Authorization: Bearer "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NTc2Nzc2MTN9.W07yXif334zgpbls9BANUi6rWCbb8KVNakWkHlZ6I18"

### Products show action

GET http:localhost:3000/products/1

### Products create action

POST http://localhost:3000/products
Content-type: application/json

{
  "name": "",
  "price": "",
  "description": "",
  "image_url": "" 
}

### Products update action

PATCH http://localhost:3000/products/1
Content-type: application/json

{
  "name": "",
  "price": "",
  "description": "",
  "image_url": "" 
}

### Product delete action 

DELETE http://localhost:3000/products/2

### Users create

POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Gina",
  "email": "Gina@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "Gina@test.com",
  "password": "password"
}