### Products index action

GET http://localhost:3000/products

### Products show action

GET http:localhost:3000/products/1

### Products create action

POST http://localhost:3000/products
Content-type: application/json

{
  "name": "",
  "price": "",
  "description": "",
  "image_url": "" 
}

### Products update action

PATCH http://localhost:3000/products/1
Content-type: application/json

{
  "name": "",
  "price": "",
  "description": "",
  "image_url": "" 
}

### Product delete action 

DELETE http://localhost:3000/products/2

### 