Supplier.create(name: "Plant Wholesale", email: "Plantwholesale@gmail.com", phone_number: "1-800-123-1234")
Supplier.create(name: "Rare Plant Wholesaler", email: "Rareplantest.com", phone_number: "1-888-123-1234")


product = Product.create({supplier_id: 1, name: "Fern 'Birds Nest Hurricane'", price: 30, description: "The Asplenium antiquum Hurricane Bird's nest fern is a relatively new variety that has a wonderful whirlwind growth habit of glossy green leaves. It prefers a degree of humidity making it ideal for adding a touch of easy-care, air-purifying greenery to kitchens and bathrooms"})
product = Product.create({supplier_id: 2, name: "Croton 'Freckles'", price: 38, description: "The colorful foliage for this variety of croton, has spots similar to freckles as it is found all over the plant including leaves and stems. Leaves start off green with light yellow spots and eventually, leaves turn bright red with light red spots" })
product = Product.create({supplier_id: 2, name: "ZZ Zamioculcas 'Black Raven'", price: 70, description: "Zamioculcas raven will survive in very low light conditions. That’s why it is suitable for use in the office or even in poorly lit rooms like bathrooms. However, for it to thrive and grow, put it in a very well-lit place while avoiding direct sunlight. Time is what makes the black ZZ plant turn dark. Fresh leaves start out bright green and gradually turn black with time"})
product = Product.create({supplier_id: 1, name: "Ficus 'Umbellata'", price: 40, description: "Ficus umbellata is known for its wide, unique heart-shaped leaves and also thin stems. This type of plant makes an excellent indoor specimen because it can grow well in medium-high light conditions and be pruned into different shapes if desired. It’s easy to care for and offers a lot of variety in color and leaf shapes"})
product = Product.create({supplier_id: 2, name: "Carnivorous 'Monkey Cup' Mini Basket", price: 30, description: "From its tendrils, you'll see globe- or tube-shaped protrusions that act as traps. In the tropics, monkeys are often seen drinking rainwater from these “pitchers” which is how it got its most popular nicknames"})
product = Product.create({supplier_id: 1, name: "Schefflera 'Variegated'", price: 20, description: "The Umbrella plant is the dwarf version of the larger schefflera acrinophylla native to Taiwan. This evergreen wields very slender stalks with oblong leaves arranged in a circular fashion at the end of each stem. This particular variegated variety will have splashes of washed out yellow on many of its leaves"})
product = Product.create({supplier_id: 2, name: "Begonia 'Pink Spotted'", price: 30, description: "Begonia Amphioxus is a small but eye-catching plant that you can never deny introducing in your garden. The beautiful plant does not bear negligence, so you need to take care of it and provide it with the right growing conditions. Begonia Amphioxus is native to Borneo, Indonesia, and is native to tropical regions. You will love to grow this plant in your household. The plant is bushy and belongs to the Begonia family. The plant’s scientific name originates from ‘amphi’ ‘oxys’, meaning that the plant has pointed ends and they are elongated as well"})

Image.create({ product_id:1, url: "https://cdn.shopify.com/s/files/1/2528/3612/products/image_png_1578146101_974x1299.png?v=1657256639"})
Image.create({ product_id:2, url: "https://cdn.shopify.com/s/files/1/2528/3612/products/6_CROTON_FRECKLES_3_974x974.jpg?v=1654050614"})
Image.create({ product_id:3, url: "https://cdn.shopify.com/s/files/1/2528/3612/products/6_ZZ_BLACK_RAVEN_3_de04daf2-121a-40ba-a7a3-b2cec7faa211_974x974.jpg?v=1654050727"})
Image.create({ product_id:4, url: "https://cdn.shopify.com/s/files/1/2528/3612/products/4_FICUS_UMBELLATA_3_3d22418b-c308-4a15-87f1-84b05dd6f692_421x421.jpg?v=1654050430"})
Image.create({ product_id:5, url:"https://cdn.shopify.com/s/files/1/2528/3612/products/CARNIVOROUS_MONKEY.CUP_MINI_BASKET_3_974x974.jpg?v=1655277522"})
Image.create({ product_id:6, url: "https://cdn.shopify.com/s/files/1/2528/3612/products/8-VARIGATEDSHEFLERA-3_421x421.jpg?v=1630011867"})
Image.create({ product_id:7, url: "https://cdn.shopify.com/s/files/1/2528/3612/products/4_BEGONIA_PINK_SPOTTED_3_300228fa-978f-4b5f-b304-12d34eb68a7c_421x421.jpg?v=1654050318"})